# Generated by Django 6.0.3 on 2026-04-26 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_deal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OsagoPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('expired', 'Истёк'), ('cancelled', 'Аннулирован')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('insured_last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия страхователя')),
                ('insured_first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя страхователя')),
                ('insured_middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество страхователя')),
                ('insured_dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения страхователя')),
                ('insured_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон страхователя')),
                ('insured_email', models.EmailField(blank=True, max_length=254, verbose_name='Email страхователя')),
                ('vehicle_make', models.CharField(blank=True, max_length=100, verbose_name='Марка ТС')),
                ('vehicle_model', models.CharField(blank=True, max_length=100, verbose_name='Модель ТС')),
                ('vehicle_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('vehicle_vin', models.CharField(blank=True, max_length=20, verbose_name='VIN')),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, verbose_name='Гос. номер')),
                ('vehicle_category', models.CharField(choices=[('B', 'B — легковые, мотоциклы'), ('C', 'C — грузовые'), ('D', 'D — автобусы'), ('E', 'E — прицепы'), ('Tb', 'Tb — троллейбусы'), ('Tm', 'Tm — трамваи')], default='B', max_length=5, verbose_name='Категория ТС')),
                ('engine_power', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мощность двигателя (л.с.)')),
                ('drivers_type', models.CharField(choices=[('limited', 'Ограниченный список'), ('unlimited', 'Без ограничений')], default='limited', max_length=20, verbose_name='Список водителей')),
                ('policy_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('policy_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('insurer_name', models.CharField(blank=True, max_length=200, verbose_name='Страховая компания')),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Страховая премия (₽)')),
                ('policy_number', models.CharField(blank=True, max_length=50, verbose_name='Номер полиса')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osago_policies', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Полис ОСАГО',
                'verbose_name_plural': 'Полисы ОСАГО',
                'ordering': ['-created_at'],
            },
        ),
    ]
